### ISSUE TITLE
detaildate这个接口缺少已报名的数据

### ISSUE THREAD

**Issue by wssgcg1213** [RedrockTeam/Date_backend#58]
![qq20150601-1 2x](https://cloud.githubusercontent.com/assets/3922719/7909163/e16d08ba-087c-11e5-8d9a-ab0a7559c2f3.png)

已报名的数据 demo:

```
[
  {nickname: "张鑫旭", head: "http://xxxx", uid: 123},
  {nickname: "张鑫旭", head: "http://xxxx", uid: 123}
]
```

**Comment by Lich2013** [comment]
https://github.com/RedrockTeam/Date_backend/blob/dev/API.md#约会信息  第8条

**Comment by wssgcg1213** [comment]
只有这里会用 考虑和在一起吧

**Comment by Lich2013** [comment]
貌似个人中心那边好像还有地方要用

**Comment by wssgcg1213** [comment]
fixed
