### ISSUE TITLE
详情接口

### ISSUE THREAD

**Issue by wssgcg1213** [RedrockTeam/Date_backend#70]
http://106.184.7.12:8002/index.php/api/date/detaildate

**Comment by wssgcg1213** [comment]
这个接口有grade_limit: [1, 2]

最好来一个grade: ["2013", "2014"]这样的参数

**Comment by Lich2013** [comment]
接口文档里这么写的:
`"grade_limit": "[1,2]", //数组!!!年级限制 1 -> 2011 2 -> 2012 3 -> 2013, 如果没有限制, grade_limit和grade_select_model就别传`

`"grade_select_model": "", //1正选(默认), 2反选,如果有年级限制就必须有这个`

这个新的grade是指?

**Comment by wssgcg1213** [comment]
我知道啊 但是这样我就要请求两个接口 然后你其他地方又是直接给的2013 2014这样的数组 我就搞不懂了

发自我的 iPhone

**Comment by Lich2013** [comment]
除了`'public/grade'`这个接口我是这么返回的, 我其他应该大概没有直接给2013 2014这样的吧....

**Comment by wssgcg1213** [comment]
so…

发自我的 iPhone

**Comment by Lich2013** [comment]
发给我的时候你`grade_limit`里面带的参数直接就该是[1,2,3,4]这样的就行了啊, 请求两个接口因为年级每年都要变, 必须动态获取吧, 但是我没想通`grade: ["2013", "2014"]`这个参数是干什么用的

**Comment by wssgcg1213** [comment]
detail接口啊，详情接口 

我显示用的 不是我给你  是你要告诉我的

发自我的 iPhone

**Comment by Lich2013** [comment]
我以为是发布接口.....好吧, 我加个grade.....

**Comment by Lich2013** [comment]
ok
`"grade_limit": [
      "1"
    ],
    "grade": [
      "2011级"
    ],`
