### ISSUE TITLE
私信接口问题

### ISSUE THREAD

**Issue by wssgcg1213** [RedrockTeam/Date_backend#72]
1. 私信列表接口字段重复 严重
2. 私信接受/拒绝之后, 未在私信详情接口中返回正确的私信已处理状态(期待返回值为0:已接受, 1: 已经拒绝, 实际返回2);

**Comment by Lich2013** [comment]
1. 私信重复问题已经解决;
2. 机智的解决了下, 状态应该没问题了

**Comment by Lich2013** [comment]
letter_id 和 to_id 是否已经修改?看request好像没改?

**Comment by wssgcg1213** [comment]
已改 好
